//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntreVoisin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITE
    {
        public ACTIVITE()
        {
            this.COMMENTAIREACTIVITE = new HashSet<COMMENTAIREACTIVITE>();
            this.FICHIERCOMPLEMENTAIRE = new HashSet<FICHIERCOMPLEMENTAIRE>();
        }
    
        public short IDACTIVITE { get; set; }
        public short IDCOMMUNAUTE { get; set; }
        public short IDUSER { get; set; }
        public string DESCRIP { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
    
        public virtual COMMUNAUTE COMMUNAUTE { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
        public virtual ACTUS ACTUS { get; set; }
        public virtual BONPLAN BONPLAN { get; set; }
        public virtual ICollection<COMMENTAIREACTIVITE> COMMENTAIREACTIVITE { get; set; }
        public virtual COVOITURAGE COVOITURAGE { get; set; }
        public virtual EVENEMENT EVENEMENT { get; set; }
        public virtual ICollection<FICHIERCOMPLEMENTAIRE> FICHIERCOMPLEMENTAIRE { get; set; }
        public virtual OBJET OBJET { get; set; }
        public virtual OBJETPERDU OBJETPERDU { get; set; }
        public virtual SERVICE SERVICE { get; set; }
        public virtual SONDAGE SONDAGE { get; set; }
    }
}
