//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntreVoisin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTUS
    {
        public short IDACTIVITE { get; set; }
        public short IDCOMMUNAUTE { get; set; }
        public string CDTYPEACTUS { get; set; }
        public string DESCRIP { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
    
        public virtual ACTIVITE ACTIVITE { get; set; }
        public virtual TYPEACTUS TYPEACTUS { get; set; }
    }
}
