//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntreVoisin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTREINTERET
    {
        public CENTREINTERET()
        {
            this.TYPECENTREINTERET = new HashSet<TYPECENTREINTERET>();
            this.UTILISATEUR1 = new HashSet<UTILISATEUR>();
        }
    
        public short IDCENTREINTERET { get; set; }
        public short IDCOMMUNAUTE { get; set; }
        public short IDUSER_ADMIN { get; set; }
        public string NOM { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public string DESCRIP { get; set; }
    
        public virtual COMMUNAUTE COMMUNAUTE { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
        public virtual ICollection<TYPECENTREINTERET> TYPECENTREINTERET { get; set; }
        public virtual ICollection<UTILISATEUR> UTILISATEUR1 { get; set; }
    }
}
