//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntreVoisin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMUNAUTE
    {
        public COMMUNAUTE()
        {
            this.ACTIVITE = new HashSet<ACTIVITE>();
            this.CENTREINTERET = new HashSet<CENTREINTERET>();
            this.UTILISATEUR1 = new HashSet<UTILISATEUR>();
        }
    
        public short IDCOMMUNAUTE { get; set; }
        public short IDUSER_ADMIN { get; set; }
        public string NOM { get; set; }
        public Nullable<decimal> ADDRESSLATITUDE { get; set; }
        public Nullable<decimal> ADDRESSLONGITUDE { get; set; }
    
        public virtual ICollection<ACTIVITE> ACTIVITE { get; set; }
        public virtual ICollection<CENTREINTERET> CENTREINTERET { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
        public virtual ICollection<UTILISATEUR> UTILISATEUR1 { get; set; }
    }
}
