//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntreVoisin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIRMATION
    {
        public CONFIRMATION()
        {
            this.UTILISATEUR1 = new HashSet<UTILISATEUR>();
        }
    
        public short IDCONFIRMATION { get; set; }
        public string CDCONFIRMATION { get; set; }
        public Nullable<short> IDUSER_CONFIRME { get; set; }
        public Nullable<bool> CONFIRME { get; set; }
    
        public virtual TYPECONFIRMATION TYPECONFIRMATION { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
        public virtual ICollection<UTILISATEUR> UTILISATEUR1 { get; set; }
    }
}
