//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntreVoisin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class entrevoisinEntities : DbContext
    {
        public entrevoisinEntities()
            : base("name=entrevoisinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVITE> ACTIVITE { get; set; }
        public virtual DbSet<ACTUS> ACTUS { get; set; }
        public virtual DbSet<BONPLAN> BONPLAN { get; set; }
        public virtual DbSet<CENTREINTERET> CENTREINTERET { get; set; }
        public virtual DbSet<COMMENTAIREACTIVITE> COMMENTAIREACTIVITE { get; set; }
        public virtual DbSet<COMMUNAUTE> COMMUNAUTE { get; set; }
        public virtual DbSet<CONFIRMATION> CONFIRMATION { get; set; }
        public virtual DbSet<COVOITURAGE> COVOITURAGE { get; set; }
        public virtual DbSet<EVENEMENT> EVENEMENT { get; set; }
        public virtual DbSet<FICHIERCOMPLEMENTAIRE> FICHIERCOMPLEMENTAIRE { get; set; }
        public virtual DbSet<MESSAGEPRIVE> MESSAGEPRIVE { get; set; }
        public virtual DbSet<OBJET> OBJET { get; set; }
        public virtual DbSet<OBJETPERDU> OBJETPERDU { get; set; }
        public virtual DbSet<SERVICE> SERVICE { get; set; }
        public virtual DbSet<SONDAGE> SONDAGE { get; set; }
        public virtual DbSet<TYPEACTUS> TYPEACTUS { get; set; }
        public virtual DbSet<TYPECENTREINTERET> TYPECENTREINTERET { get; set; }
        public virtual DbSet<TYPECONFIRMATION> TYPECONFIRMATION { get; set; }
        public virtual DbSet<TYPEOBJET> TYPEOBJET { get; set; }
        public virtual DbSet<TYPEPROPOSITIONOBJET> TYPEPROPOSITIONOBJET { get; set; }
        public virtual DbSet<TYPEPROPOSITIONSERVICE> TYPEPROPOSITIONSERVICE { get; set; }
        public virtual DbSet<TYPESERVICE> TYPESERVICE { get; set; }
        public virtual DbSet<USEROBJET> USEROBJET { get; set; }
        public virtual DbSet<USERSERVICE> USERSERVICE { get; set; }
        public virtual DbSet<UTILISATEUR> UTILISATEUR { get; set; }
    }
}
