//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntreVoisin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGEPRIVE
    {
        public short IDUSER_2 { get; set; }
        public short IDUSER_1 { get; set; }
        public short IDMESSAGE { get; set; }
        public short IDUSER_SEND { get; set; }
        public Nullable<System.DateTime> DATEENVOI { get; set; }
        public string CONTENU { get; set; }
    
        public virtual UTILISATEUR UTILISATEUR { get; set; }
        public virtual UTILISATEUR UTILISATEUR1 { get; set; }
        public virtual UTILISATEUR UTILISATEUR2 { get; set; }
    }
}
