//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntreVoisin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJET
    {
        public short IDACTIVITE { get; set; }
        public short IDCOMMUNAUTE { get; set; }
        public string CDPROPOSITIONOBJET { get; set; }
        public string CDOBJET { get; set; }
        public string TITRE { get; set; }
        public Nullable<short> PRIX { get; set; }
        public string DESCRIP { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
    
        public virtual ACTIVITE ACTIVITE { get; set; }
        public virtual TYPEOBJET TYPEOBJET { get; set; }
        public virtual TYPEPROPOSITIONOBJET TYPEPROPOSITIONOBJET { get; set; }
    }
}
