//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntreVoisin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPECONFIRMATION
    {
        public TYPECONFIRMATION()
        {
            this.CONFIRMATION = new HashSet<CONFIRMATION>();
        }
    
        public string CDCONFIRMATION { get; set; }
        public string LIBELLE { get; set; }
    
        public virtual ICollection<CONFIRMATION> CONFIRMATION { get; set; }
    }
}
