//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntreVoisin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPEOBJET
    {
        public TYPEOBJET()
        {
            this.OBJET = new HashSet<OBJET>();
            this.USEROBJET = new HashSet<USEROBJET>();
        }
    
        public string CDOBJET { get; set; }
        public string LIBELLEOBJET { get; set; }
    
        public virtual ICollection<OBJET> OBJET { get; set; }
        public virtual ICollection<USEROBJET> USEROBJET { get; set; }
    }
}
