//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntreVoisin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERSERVICE
    {
        public short NOSERVICE { get; set; }
        public short IDUSER { get; set; }
        public string CDSERVICE { get; set; }
        public Nullable<bool> CONFIDENTIEL { get; set; }
        public string NOM { get; set; }
    
        public virtual TYPESERVICE TYPESERVICE { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
