//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntreVoisin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILISATEUR
    {
        public UTILISATEUR()
        {
            this.ACTIVITE = new HashSet<ACTIVITE>();
            this.CENTREINTERET = new HashSet<CENTREINTERET>();
            this.COMMENTAIREACTIVITE = new HashSet<COMMENTAIREACTIVITE>();
            this.COMMUNAUTE = new HashSet<COMMUNAUTE>();
            this.CONFIRMATION = new HashSet<CONFIRMATION>();
            this.MESSAGEPRIVE = new HashSet<MESSAGEPRIVE>();
            this.MESSAGEPRIVE1 = new HashSet<MESSAGEPRIVE>();
            this.MESSAGEPRIVE2 = new HashSet<MESSAGEPRIVE>();
            this.USEROBJET = new HashSet<USEROBJET>();
            this.USERSERVICE = new HashSet<USERSERVICE>();
            this.CENTREINTERET1 = new HashSet<CENTREINTERET>();
            this.COMMUNAUTE1 = new HashSet<COMMUNAUTE>();
            this.UTILISATEUR1 = new HashSet<UTILISATEUR>();
            this.UTILISATEUR2 = new HashSet<UTILISATEUR>();
        }
    
        public short IDUSER { get; set; }
        public short IDCONFIRMATION { get; set; }
        public string PSEUDO { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public Nullable<System.DateTime> DATENAISSANCE { get; set; }
        public Nullable<float> ADDRESSLATITUDE { get; set; }
        public Nullable<float> ADDRESSLONGITUDE { get; set; }
        public Nullable<short> ADDRESSNO { get; set; }
        public string ADDRESSROUTE { get; set; }
        public string ADDRESSLOCALITY { get; set; }
        public string ADDRESSPOSTALCODE { get; set; }
        public string ADDRESSCOMPLEMENT { get; set; }
        public string PHOTO { get; set; }
        public Nullable<bool> CONFIDENTIEL { get; set; }
        public Nullable<bool> CONNECTE { get; set; }
    
        public virtual ICollection<ACTIVITE> ACTIVITE { get; set; }
        public virtual ICollection<CENTREINTERET> CENTREINTERET { get; set; }
        public virtual ICollection<COMMENTAIREACTIVITE> COMMENTAIREACTIVITE { get; set; }
        public virtual ICollection<COMMUNAUTE> COMMUNAUTE { get; set; }
        public virtual ICollection<CONFIRMATION> CONFIRMATION { get; set; }
        public virtual CONFIRMATION CONFIRMATION1 { get; set; }
        public virtual ICollection<MESSAGEPRIVE> MESSAGEPRIVE { get; set; }
        public virtual ICollection<MESSAGEPRIVE> MESSAGEPRIVE1 { get; set; }
        public virtual ICollection<MESSAGEPRIVE> MESSAGEPRIVE2 { get; set; }
        public virtual ICollection<USEROBJET> USEROBJET { get; set; }
        public virtual ICollection<USERSERVICE> USERSERVICE { get; set; }
        public virtual ICollection<CENTREINTERET> CENTREINTERET1 { get; set; }
        public virtual ICollection<COMMUNAUTE> COMMUNAUTE1 { get; set; }
        public virtual ICollection<UTILISATEUR> UTILISATEUR1 { get; set; }
        public virtual ICollection<UTILISATEUR> UTILISATEUR2 { get; set; }
    }
}
